import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plex_mono = IBM_Plex_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-plex-mono'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${plex_mono.variable} antialiased`} lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
